apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: powerstore
  namespace: powerstore
spec:
  driver:
    csiDriverType: "powerstore"
    csiDriverSpec:
      fSGroupPolicy: "ReadWriteOnceWithFSType"
      storageCapacity: true
    configVersion: v2.10.1
    authSecret: powerstore-config
    replicas: 1  # For SNO, typically set replicas to 1
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    forceRemoveDriver: true
    common:
      image: "dellemc/csi-powerstore:v2.10.1"
      imagePullPolicy: IfNotPresent
      envs:
        - name: X_CSI_POWERSTORE_NODE_NAME_PREFIX
          value: "csi-node"
        - name: X_CSI_FC_PORTS_FILTER_FILE_PATH
          value: "/etc/fc-ports-filter"
        - name: KUBELET_CONFIG_DIR
          value: /var/lib/kubelet
        - name: CSI_LOG_LEVEL
          value: debug
    sideCars:
      - name: provisioner
        image: registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
        args: ["--volume-name-prefix=csivol"]
      - name: attacher
        image: registry.k8s.io/sig-storage/csi-attacher:v4.5.0
      - name: registrar
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
      - name: resizer
        image: registry.k8s.io/sig-storage/csi-resizer:v1.10.0
      - name: snapshotter
        image: registry.k8s.io/sig-storage/csi-snapshotter:v7.0.1
      - name: csi-metadata-retriever
        image: dellemc/csi-metadata-retriever:v1.7.3
      - name: external-health-monitor
        enabled: false
        args: ["--monitor-interval=60s"]
        image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.11.0

    controller:
      envs:
        - name: X_CSI_NFS_ACLS
          value: "0777"
        - name: X_CSI_HEALTH_MONITOR_ENABLED
          value: "false"
        - name: X_CSI_POWERSTORE_EXTERNAL_ACCESS
          value: ""
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

    node:
      envs:
        - name: "X_CSI_POWERSTORE_ENABLE_CHAP"
          value: "false"
        - name: X_CSI_HEALTH_MONITOR_ENABLED
          value: "false"
        - name: X_CSI_POWERSTORE_MAX_VOLUMES_PER_NODE
          value: "0"
        # iSCSI specific configurations
        - name: "X_CSI_ISCSI_TARGET_PORTAL"
          value: "192.168.100.11"
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

  modules:
    - name: resiliency
      enabled: false
      configVersion: v1.9.1
      components:
        - name: podmon-controller
          image: dellemc/podmon:v1.9.1
          imagePullPolicy: IfNotPresent
          args:
            - "--labelvalue=csi-powerstore"
            - "--arrayConnectivityPollRate=60"
            - "--skipArrayConnectionValidation=false"
            - "--driverPodLabelValue=dell-storage"
            - "--ignoreVolumelessPods=false"
            - "--arrayConnectivityConnectionLossThreshold=3"
            - "--csisock=unix:/var/run/csi/csi.sock"
            - "--mode=controller"
            - "--driver-config-params=/powerstore-config-params/driver-config-params.yaml"
            - "--driverPath=csi-powerstore.dellemc.com"
        - name: podmon-node
          image: dellemc/podmon:v1.9.1
          imagePullPolicy: IfNotPresent
          envs:
            - name: "X_CSI_PODMON_API_PORT"
              value: "8083"
          args:
            - "--labelvalue=csi-powerstore"
            - "--arrayConnectivityPollRate=60"
            - "--leaderelection=false"
            - "--driverPodLabelValue=dell-storage"
            - "--ignoreVolumelessPods=false"
            - "--csisock=unix:/var/lib/kubelet/plugins/csi-powerstore.dellemc.com/csi_sock"
            - "--mode=node"
            - "--driver-config-params=/powerstore-config-params/driver-config-params.yaml"
            - "--driverPath=csi-powerstore.dellemc.com"
